import 'package:abu_sahiy/view/main_category/model/main_category_model.dart';

class MainCategoryRepository{
  static Map<String,List<MainCategoryModel>> categoryMap={
    'Ayollar kiyimi':[
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
      MainCategoryModel(name: 'women', photoPath: 'women_clothes.jpg'),
    ],
    'Erkaklar kiyimi':[
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
      MainCategoryModel(name: 'men', photoPath: 'men_clothes.jpg'),
    ],
    'Bolalar kiyimi':[
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
      MainCategoryModel(name: 'kids', photoPath: 'kids_clothes.jpg'),
    ],
    'Elektronika':[
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
      MainCategoryModel(name: 'electroniks', photoPath: 'electroniks.jpg'),
    ],
    'Oyoq kiyimlar':[
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
      MainCategoryModel(name: 'shoes', photoPath: 'shoes.jpg'),
    ],
  };
}